### ISSUE TITLE
PI CAP MPR121 library interrupt on wiringpi input 0

### ISSUE THREAD

**Issue by filoteo-2000** [BareConductive/wiringpi-mpr121#1]
Hi, I couldn't find any support documentation regarding the libraries for the PI CAP and Im having some issues using the libraries. 

I have been able to compile the libraries from the source. (The ones in C) though, I still haven't been able to properly compile the python wrapping ones. So in the mean time I'm sticking to cpp examples only. 

Also I can run the picap-simple-touch-cpp example but found that the application has not been able to detect the interruption that is supposed to arrive on the wiringpi pin 0. I bypassed the interrupt condition and I'm able to see the messages when I touch the capacitance sensors. So the PI CAP board is operational. I was wondering If you could give me any insight into how is this line being driven by the board and driver. I made a simple program that uses digitalRead(0) successfully so Im sure the pin on the board (the 'raspberry') works properly. 

I'm using the PI CAP on a system that is not officially supported but with the proliferation of similar boards I think that any insight into how to get them working might be beneficial for the community. I know this might not be an issue strictly speaking but I couldn't find where to ask about this. 

Environment 
System: Odroid XU4 (a SoC board similar to a Raspberry but in steroids. it uses an Exynos chip). 
OS: Ubuntu 4.14 LTS

**Comment by stefandz** [comment]
The code that implements MPR121.touchStatusChanged() is [here](https://github.com/BareConductive/wiringpi-mpr121/blob/public/src/MPR121.cpp#L412). As you can see, this is a simple call of an or-ed internally generated touch variable and a digital read on the pin itself. The internally generated variable is updated to keep track of the touch status whenever an I2C read would normally clear it.

As for why your system isn't correctly reading this, it is hard to say. We don't have an Odroid here to test with and there is nothing clear to indicate why there would be a difference in behaviour. Does WiringPi officially support your board?

You should also note that the Pi Cap doesn't have an external pullup for the open-drain interrupt pin (see the schematic [here](https://github.com/BareConductive/picap_cad_files/blob/public/schematic/Pi_Cap.pdf)). It may be that our code for setting the interrupt pin [here](https://github.com/BareConductive/wiringpi-mpr121/blob/public/src/MPR121.cpp#L404) doesn't correctly function for the Odroid - but I can't say for sure.

I am happy to answer any other questions you may have regarding this or to try and help in whatever way I can, but without an Odroid it's going to be pretty hard for me to debug!
